### ISSUE TITLE
Preliminary benchmark on LeNet CNN trained on MNIST

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [apple/tensorflow_macos#10]
I run some preliminary test with a simple LeNet CNN Model trained on MNIST dataset.

I tested on both CPU and GPU on a Mac Mini M1 and Intel based MacBook Pro (i7 - 6 core - Radeon 5300M).

I forced TF to disable eager execution and tried with different batch parameters trying to optimize GPU memory usage and also trying to measure/understand also memory marshaling cost.  More or less I got the same distribution on the different tests.  Probably a more complex model may provide better understanding on these tradeoff.

I've also compared results of same model trained with Colab GPU and with CoreML. CoreML is trained as all other test on all layers and I've tested it on M1 and iPhone 11.  CoreML as expected as very similar performance to this accelerator based on MLCompute as they both use the same Metal/BNNS api.

I'll test tomorrow on a well know GPU and update results.

For my understanding these results are completely inline with my expectations but I would love to see other point of view.

<img width="1294" alt="benchmark" src="https://user-images.githubusercontent.com/8699190/99632365-f2a9bf00-29f1-11eb-8e86-137423e268db.png">

**Comment by qixiang109** [comment]
some post says the M1 chip is on a par with Nvidia 1080 or 1080Ti, but it seems your benchmark doesn't suggest that...

**Comment by JacopoMangiavacchi** [comment]
I think the model I used is to trivial to generalize but I wanted to start with a simple one as I wanted to compare also with the CoreML runtime and it's a little bit more complex to build fully trainable models in Core ML.

**Comment by dennywangtenk** [comment]
iPhone 11? That's funny. 

Agree CIFAR or ImageNet subset + Deeper model could tell more.

**Comment by dkgaraujo** [comment]
@JacopoMangiavacchi if you want to share the code I could run the same test in my machine as well (2019 16' i9 with Radeon 5500) to complement your table.

**Comment by JacopoMangiavacchi** [comment]
@dkgaraujo 

```python
import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

from tensorflow.python.compiler.mlcompute import mlcompute
mlcompute.set_mlc_device(device_name='gpu')

import numpy as np
import pandas as pd
from numpy import unique
from numpy import argmax
from tensorflow.keras.datasets.mnist import load_data
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
import time

train = pd.read_csv("./Data/mnist_train.csv", header=None)
test = pd.read_csv("./Data/mnist_test.csv", header=None)

trainX = train[train.columns[1:]].to_numpy().reshape((-1, 28, 28))
trainy = train[train.columns[0]].to_numpy()
testX = test[test.columns[1:]].to_numpy().reshape((-1, 28, 28))
testy = test[test.columns[0]].to_numpy()

print('Train: X=%s, y=%s' % (trainX.shape, trainy.shape))
print('Test: X=%s, y=%s' % (testX.shape, testy.shape))

trainX = trainX.reshape((trainX.shape[0], trainX.shape[1], trainX.shape[2], 1))
testX = testX.reshape((testX.shape[0], testX.shape[1], testX.shape[2], 1))

in_shape = trainX.shape[1:]
in_shape

n_classes = len(unique(trainy))
n_classes

# Normalize
trainX = trainX.astype('float32') / 255.0
testX = testX.astype('float32') / 255.0

# Create CNN Model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=in_shape))
model.add(MaxPool2D((2, 2), strides=(2,2)))
model.add(Conv2D(32, (2, 2), activation='relu', kernel_initializer='he_uniform', input_shape=in_shape))
model.add(MaxPool2D((2, 2), strides=(2,2)))
model.add(Flatten())
model.add(Dense(500, activation='relu', kernel_initializer='he_uniform'))
# model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='softmax'))

model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

start_time = time.time()
model.fit(trainX, trainy, epochs=10, batch_size=128, verbose=1)
elapsed_time = time.time() - start_time

print(f"Time: {elapsed_time}")

# Evaluate
loss, acc = model.evaluate(testX, testy, verbose=0)
print('Accuracy: %.3f' % acc)
```

**Comment by water-vapor** [comment]
MacBook Pro 16 i9-9980HK with 5500M, 15s per epoch with CPU only; 13s per epoch with GPU(eager mode on); python crash with GPU(eager mode off) (NSRangeException somewhere).

**Comment by dkgaraujo** [comment]
Thanks @JacopoMangiavacchi. Just to make sure we are running the exact same MNIST dataset (there might be various versions of it due to resize, etc), what was your source so I can download the same data?

**Comment by lyp741** [comment]
Thanks @JacopoMangiavacchi, I test it using my 16inch Macbook pro with 5500M 8G. It uses 108s to complete the task. And by the way, can you explain what the first figure shows?

**Comment by JL1829** [comment]
Don't know why my 2018 15"560x 4GB cannot be utilised, both `mlcompute.set_mlc_device(device_name='cpu')` and `mlcompute.set_mlc_device(device_name='gpu')` run time is around 140 seconds.

**Comment by bryanlimy** [comment]
@JL1829 I have the exact same system you have and I am able to train a similar model with the dGPU.

**Comment by dkgaraujo** [comment]
I ran a different CNN on tf-mac CPU, GPU and on plaidML. The codes (as well as the caveats) are in this repository [here](https://github.com/dkgaraujo/TensorflowMacOSBenchmark). Bottom line is:

```
Training a simple CNN model with gpu: 237.959 sec elapsed
Training a simple CNN model with cpu: 211.433 sec elapsed
Training a simple CNN model with plaidml using the GPU: 483.239 sec elapsed
```

**Comment by pcuenca** [comment]
I tested this code on a 2020 iMac with a Radeon Pro 5700 XT (16 GB) GPU, and got about 75s when using device `gpu`. If I used `any`, then I got some modest improvements (~73s) which I can't explain. I expected more of this GPU, but this is a very exciting direction nonetheless.

@JacopoMangiavacchi In the case of the M1, does using `any` attempt to engage the Neural Engine, as it does in iOS? Or is it just a synonym for `gpu`?

**Comment by JL1829** [comment]
@bryanlimy I couldn't get it run, would you please share you installation steps

**Comment by bryanlimy** [comment]
@JL1829 I followed the installation instruction in the README of this repo and it worked just fine. I also tried to use conda and it works too https://github.com/apple/tensorflow_macos/issues/3#issuecomment-730315477

**Comment by ticlazau** [comment]
Hello, I am trying to run on MacBook Pro with Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz, but I am getting this error: 

`760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784) have mixed types.Specify dtype option on import or set low_memory=False.
Train: X=(60001, 28, 28), y=(60001,)
Test: X=(10001, 28, 28), y=(10001,)
Traceback (most recent call last):
  File "LeNet-MNIST-benchmark.py", line 37, in <module>
    n_classes = len(unique(trainy))
  File "<__array_function__ internals>", line 5, in unique
  File "/Users/coredump/tensorflow_macos_venv/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 263, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/Users/coredump/tensorflow_macos_venv/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 311, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'int' and 'str'`

Is related with: n_classes = len(unique(trainy))

Any advice?

Thx, 
FM

**Comment by JacopoMangiavacchi** [comment]
@ticlazau set header=1 in in read_csv()

@JL1829 full instructions to install on conda here https://github.com/apple/tensorflow_macos/issues/3#issuecomment-730315477

@pcuenca ML Compute do not use the NE. My educated guess is that depending on complexity of the model of course but 'any' tend to prefer 'cpu' most of the time.  M1/A* CPU matrix multiplication acceleration is super fast, some time faster than gpu apparently.  But a more complex model architecture may results with completely different numbers I guess.

**Comment by ticlazau** [comment]
Here are my results on MacBookPro ( i7-8569U CPU @ 2.80GHz)

59999/59999 [==============================] - 12s 202us/sample - loss: nan - accuracy: 0.0987
Time: 121.92892122268677

Notice:
- CPU utilization is 40-45% during the test
- warning: This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2 AVX AVX2 FMA

**Comment by anhornsby** [comment]
Some more results...

Macbook Pro 16" 2019 2.6 GHz 6-Core 16GB with AMD Radeon Pro 5300M GPU:

GPU: 113.30 seconds
CPU (running outside of venv): 117.14 seconds

**Comment by lutchu** [comment]
@JacopoMangiavacchi this example was super helpful for validating the setup, thanks!

I am just getting started with TF so this might be a very basic question - if I change the compute device  to the CPU, even though the execution time comes down the model is only ~10% accuracy after 10 epochs. For comparison, the accuracy with the GPU execution was around 99%. Are there additional changes that are needed to get the CPU computation to work properly?

**Comment by ayman** [comment]
Macbook Pro 16" 2019 2.3 GHz 8-Core Intel Core i9, 32 GB, AMD Radeon Pro 5500M:
```
GPU: 108.75
CPU: 171.79
```
 (averaging 3 runs...tracks well with the graph)

> @dkgaraujo: Just to make sure we are running the exact same MNIST dataset (there might be various versions of it due to resize, etc), what was your source so I can download the same data?

I'm assuming it's Joseph Redmon's [MNIST as CSV](https://pjreddie.com/projects/mnist-in-csv/).

**Comment by JL1829** [comment]
Just some update:
MacBook Pro 15" 2018 2.6 GHz 6-Core Intel Core i7, 16GB, AMD Radeon Pro 560X 4 GB

```shell
GPU: 150.58
CPU: 160
```

Well, not much different.

**Comment by JL1829** [comment]
> Just some update:
> MacBook Pro 15" 2018 2.6 GHz 6-Core Intel Core i7, 16GB, AMD Radeon Pro 560X 4 GB
> 
> ```shell
> GPU: 150.58
> CPU: 160
> ```
> 
> Well, not much different.

Follow up test:

Same Devices, using Official TensorFlow Ver 2.3.1 CPU version
The performance is: 
```shell
121.84 seconds
```

You guys have similar symptoms ?

**Comment by kennyfrc** [comment]
Tested this on MacBook Pro (13-inch, 2019), 2.4 GHz Quad-Core Intel Core i5, 8GB RAM, Radeon RX 5700 XT 8 GB:
```
GPU: 126.62 (accuracy: 0.9977)
CPU: 139.83 (accuracy: 0.0987)
```

**Comment by HenryYoon** [comment]
By the way, what kind of stuff do you use for m1 mac mini? I heard that the performance is different from the memory capacity: 8gb of 16gb.

**Comment by yarmun** [comment]
> Tested this on MacBook Pro (13-inch, 2019), 2.4 GHz Quad-Core Intel Core i5, 8GB RAM, Radeon RX 5700 XT 8 GB:
> 
> ```
> GPU: 126.62 (accuracy: 0.9977)
> CPU: 139.83 (accuracy: 0.0987)
> ```

1) Why is the CPU accuracy so low vs GPU?  I am getting similar numbers too.

**Comment by yarmun** [comment]
Macbook Air 2020 M1 16GB Ram

GPU: 90.29 (accuracy: 0.989)
CPU: 61.75  (accuracy: 0.098)

How did you guys on M1 run the code with pandas inside the tensorflow_macos_venv?  I am unable to run pandas in the tensorflow_macos_venv.  I had to save the df by np.save first outside the environment, then np.load to run TF inside the environment.

**Comment by yarmun** [comment]
> Tested this on MacBook Pro (13-inch, 2019), 2.4 GHz Quad-Core Intel Core i5, 8GB RAM, Radeon RX 5700 XT 8 GB:
> 
> ```
> GPU: 126.62 (accuracy: 0.9977)
> CPU: 139.83 (accuracy: 0.0987)
> ```

Why is the CPU accuracy so low vs GPU? I am getting similar numbers too.

Macbook Air 2020 M1 16GB Ram
GPU: 90.29 (accuracy: 0.989)
CPU: 61.75 (accuracy: 0.098)

Also, how did you guys on M1 run the code with pandas inside the tensorflow_macos_venv? I am unable to run pandas in the tensorflow_macos_venv. I had to save the df by np.save first outside the environment, then np.load to run TF inside the environment.
