### ISSUE TITLE
NaNs not handled at all in bundled numpy

### ISSUE THREAD

**Issue by ramicaza** [apple/tensorflow_macos#129]
The numpy bundled with the package doesn't seem to handle NaNs at all :/

Firstly, if there is any NaN at all, printing the array fails. I tried to get around this by using np.nan_to_num to remove all nans from my data but this also fails.  Finally, I tried to loop through the data and use np.isnan to replace them and isnan always returns False even if there is a nan!

Easy to reproduce, just type "arr=np.array([1,np.NaN,2]);print(arr)" in an interactive terminal and watch the print fail.

This wouldn't be a big issue if we were able to use the arm python 3.9 bundled with miniforge, however the installer only allows you to point to python3.8 executables.

Also, as a side note, this repo doesn't offer any information about the libraries bundled in here including numpy... I'm curious if these have been optimized to make use of the neural engine or are they bundled for some other reason?

**Comment by enea-ceolini** [comment]
Same here! I noticed cause pandas was not behaving correctly when doing .dropna().

I checked and numpy 1.19.5 compiled for arm64 on python 3.8 from miniforge behaves as expected (thus correctly identified NaNs). The bundled version of numpy is 1.18.5. Maybe is just a matter of recompiling it.

**Comment by ramicaza** [comment]
The miniforge python numpy works like you said @enea-ceolini.  I couldn't figure out how to get tf_macos to use that version of numpy but it turns out the trick is to install with --no-dependencies.  Following #153 got me up and running :)
