### ISSUE TITLE
 no suitable image found

### ISSUE THREAD

**Issue by ansarisam** [apple/tensorflow_macos#130]
I installed Tensorflow using the command:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"`
 I could never had a working tensorflow install on MacBook AIr with M1. When I import tensorflow, I get the following error

>>> import tensorflow as tf
Traceback (most recent call last):
  File "/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/ansarisam/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ramicaza** [comment]
Make sure you select the apple distributed version of python as the interpreter.  I'm guessing you are using the homebrew installed python which is x86.

This is outlined in the readme of this repo but you can download the installer script from the [releases](https://github.com/apple/tensorflow_macos/releases) and then specify the --python option to point it to the right python interpreter (should be located at /usr/bin/python3).  If you don't have this interpreter, it can be obtained through Xcode command line tools.

**Comment by HandsomeMan-LAX** [comment]
有什么解决办法吗，遇到了同样的问题

**Comment by suluz** [comment]
I solved this problem in two steps. Step 1. Use the arm version of python3 (downloaded with the Xcode command line tools, as mentioned in the Readme) to create a virtual environment. When doing this, you should specify it path. For me, it's /usr/bin/python3. Step 2. Install this m1 tensorflow by the command listed in the readme. During the installation, specify the virtual environment you just created.

**Comment by HandsomeMan-LAX** [comment]
有具体步骤详解吗，小白一个

**Comment by ansarisam** [comment]
Suggestions provided in this thread solved the issue. Thank you all.

**Comment by johnson7788** [comment]
you can check your pip freeze and uname -m， make sure both are arm64
