### ISSUE TITLE
This has become harder to use?

### ISSUE THREAD

**Issue by ben-xD** [apple/tensorflow_macos#142]
Hi, I notice now users can either
1. Download the script every time they want to create a venv (300MB each time)
2. Or manually download the files and put it in the right place in the repo, and then run it.

It seems like before, cloning the repo and running the script just worked. It was much easier. Not sure what's gone wrong here, but thats my feedback. I for one, have downloaded your assets twice because of this. 

EDIT: I might be wrong, maybe the first time i used this, i just downloaded the archive. I think the `download_and_install.sh` is wasteful for bandwidth.

**Comment by anna-tikhonova** [comment]
Thank you for your feedback. We are planning to improve the installation procedure in the upcoming release.
