### ISSUE TITLE
Simple way to turn off acceleration

### ISSUE THREAD

**Issue by karlglazebrook** [apple/tensorflow_macos#165]
Hi there,

Is there a simple way to turn off the ML_Compute acceleration and revert to 'stock' tensorflow?

This would be for benchmarking, but also checking for issues with resukts

**Comment by walleym** [comment]
If I understand the documentation from the readme file. It should be something to do with this: TF_DISABLE_MLC_EAGER=“;Op1;Op2;...” I believe that you can use that to turn off acceleration for specific ops. Not sure if there is a blanket way of doing this for all

**Comment by anna-tikhonova** [comment]
Thank you for reporting this. We will provide a simple way to turn off acceleration in the upcoming update.

**Comment by karlglazebrook** [comment]
Thanks that would be welcome! It seems official tensorflow has not yet caught up with arm64 (based on that 'pip install' does not work yet).

**Comment by ManuelSchneid3r** [comment]
If 0.1-alpha3 fixes this issue, how can we disable acceleration then?
