### ISSUE TITLE
The installation seems to expect Python 3.8 and fails when 3.9 is installed

### ISSUE THREAD

**Issue by duncangroenewald** [apple/tensorflow_macos#17]
See below:

~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"

Installation script for pre-release tensorflow_macos 0.1alpha0.  Please visit https://github.com/apple/tensorflow_macos 
for instructions and license information.

This script will download tensorflow_macos 0.1alpha0 and needed binary dependencies, then install them into a new 
or existing Python 3.8 virtual enviornoment.
Continue [y/N]? y

Downloading installer.
/var/folders/_j/j0707trd5p5d1skxsr5hkl600000gn/T/tmp.0RRbRquc ~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   659  100   659    0     0   1387      0 --:--:-- --:--:-- --:--:--  1384
100  316M  100  316M    0     0  1517k      0  0:03:33  0:03:33 --:--:--  695k
Extracting installer.
Path to new or existing virtual environment [default: /Users/xxxxxxxxxxxxxxx/tensorflow_macos_venv/]: 
##############################################################

ERROR: Error retrieving python version, or python executable /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 not version 3.8.  Please specify a Python 3.8 executable with the --python option.

Error running installation script with default options.  Please fix the above errors and proceed by running 

  /var/folders/_j/j0707trd5p5d1skxsr5hkl600000gn/T/tmp.0RRbRquc/tensorflow_macos/install_venv.sh --prompt

**Comment by hoytak** [comment]
Thanks for pointing this out.  I updated the README file to list Python 3.8 in the requirements.

**Comment by lioncap55** [comment]
I have the same issue. I can not fix it. Please help.
