### ISSUE TITLE
Keyword arguments "activation", "recurrent_activation" and "recurrent_dropout" for layers.GRU causes InvalidArgumentError during training

### ISSUE THREAD

**Issue by atw1020** [apple/tensorflow_macos#170]
**Description**

When GRU units are initialized with non-default values of "activation", "recurrent_activation" and "recurrent_dropout" causes a `tf.errors.InvalidArgumentError` during training. 

**Error**
```
 Inputs to operation gradient_tape/model_1/gru_1/while/model_1/gru_1/while_grad/body/_174/gradient_tape/model_1/gru_1/while/gradients/AddN_1 of type AddN must have the same size and shape.  Input 0: [1,256] != input 1: []
	 [[{{node gradient_tape/model_1/gru_1/while/model_1/gru_1/while_grad/body/_174/gradient_tape/model_1/gru_1/while/gradients/AddN_1}}]] [Op:__inference_train_function_4694]
```

**Workaround**

If you experience this issue yourself, the only workaround I have found is to only use the default activation, recurrent activation and recurrent dropout. Default activation functions are a minor concern but the inability to use dropout on recurrent GRUs is a big limitation.

**Code to Reproduce**
```python
"""

Author: Arthur Wesley

"""

import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.models import Model

x = tf.random.uniform(shape=(1, 5, 512))
y = tf.random.uniform(shape=(1, 256))

# test GRUs

input_layer = layers.Input(shape=(None, 512))

RNNs = [layers.GRU(256), # works
        layers.GRU(256,
                   activation="relu"), # fails
        layers.GRU(256,
                   dropout=0.2), # works
        layers.GRU(256,
                   recurrent_activation="relu"), # fails
        layers.GRU(256,
                   recurrent_dropout=0.2)] # fails

        # layers.LSTM(256,
        #             activation="relu"), # gives a different issue (link)]

for RNN in RNNs:

    RNN = RNN(input_layer)

    model = Model(inputs=input_layer,
                  outputs=RNN)
    model.compile(optimizer="adam",
                  loss="mse")

    try:
        model.fit(x, y,
                  verbose=0)
        print(RNN.name, "succeeded")
    except tf.errors.InvalidArgumentError as E:
        print(RNN.name, "failed")

```

**Expected Erroneous Output**
```
gru/PartitionedCall:0 succeeded
gru_1/strided_slice_3:0 failed
gru_2/PartitionedCall:0 succeeded
gru_3/strided_slice_3:0 failed
gru_4/strided_slice_3:0 failed
```

**Comment by anna-tikhonova** [comment]
Thank you very much for reporting this issue. We will investigate and report back.

**Comment by atw1020** [comment]
After updating to the February Release, I get a new error

```
NotImplementedError: Cannot convert a symbolic Tensor (gru/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Comment by takgoya** [comment]
> After updating to the 0.1alpha-2 release I get a different error
> 
> ```
> NotImplementedError: Cannot convert a symbolic Tensor (gru/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
> ```
> 
> I can still replicate the issue on my 0.1alpha-1 release though

I'm getting the same error when trying to implement LSTM layer (using 0.1alpha-2 release).

`NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
`

**Comment by matt-audio** [comment]
I also got the same error with just simple GRU funcution, if only Dense, it is ok.
"
NotImplementedError: Cannot convert a symbolic Tensor (gru/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
"
This is simple code:
    feature_input = keras.Input( shape =(None,257) , name = 'feature_input')
    gru1 = keras.layers.GRU(257, return_sequences=True)(feature_input)
    out = keras.layers.Dense(257,activation='sigmoid')(gru1)
    model = keras.Model( feature_input , out)

**Comment by atw1020** [comment]
My issue has been fixed in 01-alpha3. 

```
gru/PartitionedCall:0 succeeded
gru_1/strided_slice_3:0 succeeded
gru_2/PartitionedCall:0 succeeded
gru_3/strided_slice_3:0 succeeded
gru_4/strided_slice_3:0 succeeded
```
