### ISSUE TITLE
oneAPI DNN Usage

### ISSUE THREAD

**Issue by ChristianLagares** [apple/tensorflow_macos#18]
I am not sure if this is the appropriate forum to post this question, but I am curious with the oneDNN message that is printed even when GPU is selected. Further, oneAPI is not officially supported on macOS. Is this message correct? 

`This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2 AVX AVX2 FMA`

Also, I'm not certain if a specific GPU can be selected or if I have to disable dynamic GPU switch to force dGPU usage.

**Comment by anna-tikhonova** [comment]
This message is being printed out by TensorFlow. We have no control over this message. The wheels we are providing have not been configured or built to use oneDNN.

**Comment by ChristianLagares** [comment]
Thanks for the quick response!
