### ISSUE TITLE
Install alpha03 fails

### ISSUE THREAD

**Issue by hannesa2** [apple/tensorflow_macos#187]
Hmm, I tried to update to new version, but it fails.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/3314607/109865912-f2fa5d00-7c64-11eb-9ae3-17ac6614636f.png">

Any idea, how to solve this ?
I already did  `rm -rf  /var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/tmp.*` but it doesn't help

**Comment by hannesa2** [comment]
`curl -LO https://github.com/apple/tensorflow_macos/releases/download/v0.1alpha3/tensorflow_macos-0.1alpha3.tar.gz`

comes with this content

`cat tensorflow_macos-0.1alpha3.tar.gz`

> Not Found%

**Comment by tahuang1991** [comment]
the same thing happened for me (I am using MacOS 11.2.1 and python is 3.8.8)
Downloading installer.
/var/folders/43/4yvdbknj5h3219s8cr4nvlm00000gn/T/tmp.QFjzzUTj ~/HEP_packages/tensorflow_macos
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     27      0 --:--:-- --:--:-- --:--:--    27
Extracting installer.
tar: Error opening archive: Unrecognized archive format

**Comment by hannesa2** [comment]
I found it.
alpha03 has (still) no artifacts

![image](https://user-images.githubusercontent.com/3314607/109870558-8b471080-7c6a-11eb-865a-87eb64565179.png)

**Comment by hannesa2** [comment]
Sorry, I was too fast.
Now it works
