### ISSUE TITLE
Install alpha03 comes with dependencies error

### ISSUE THREAD

**Issue by hannesa2** [apple/tensorflow_macos#188]
`scripts/download_and_install.sh ` and 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/3314607/109871964-0fe65e80-7c6c-11eb-8a05-14d55fee2f8c.png">

runs into

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/3314607/109871878-f218f980-7c6b-11eb-9b40-e3e35a435da9.png">

I've the fear of tons of follow up errors.

Does someone has a hint how to solve it ?

**Comment by tahuang1991** [comment]
i can install alpha3 on MacOS 11.2.1 but i had another issue.  

Just curious about your installation: why it was saying "0.1a2 requires"...   I remember you were installing the alpha3?

**Comment by hannesa2** [comment]
@tahuang1991 
Thank you for the hint !

I installed on top of existing alha02 virtual env, that was the issue.

I run `rm -rf /Users/hannes/tensorflow_macos_venv` and installed again.

Now it works. Thank you

**Comment by tahuang1991** [comment]
@hannesa2 
you are welcome!  I am wondering what your environment is ?  I am working with MacOs 11.2.1 and python3.8.8, but right now i had some issues with running tensorflow.  it seems to be complicate but maybe it really have strict dependency on python version. 

Thanks in advance!
