### ISSUE TITLE
Failed to run tensorflow with alpha3

### ISSUE THREAD

**Issue by tahuang1991** [apple/tensorflow_macos#189]
**Hello,   I am  using python3.8.8 and MacOS 11.2.1, M1 chip.   I installed the alpha3 without error and then activated the virtual environment. However i still failed to import tensorflow with python3.8.8**

 python3 -c 'import tensorflow as tf; print(tf.__version__)'
Traceback (most recent call last):
  File "/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/taohuang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by hannesa2** [comment]
I don't know, if it helps you. But this is my output 

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/3314607/109874532-86d12680-7c6f-11eb-9d8c-592cc9598e73.png">

**Comment by csancineto** [comment]
I had the same problem when I tried to install alpha2. To solve it, I had to:
1.  remove all Python 3.x installations (they were x86 versions); 
2. install Xcode script Command Line tools (it install Python 3.8.2 using Arm);
3. Follow regular instructions on the original post.

**Comment by tahuang1991** [comment]
Problem solved after following @csancineto 's suggestion. 

to install python from  command line tool using brew:

brew install python@3.8
brew link python@3.8

then i got python3.8.8 installed.
