### ISSUE TITLE
Which machines benefit from using this fork?

### ISSUE THREAD

**Issue by andportnoy** [apple/tensorflow_macos#2]
Will MacBook Pros with AMD GPUs see a performance improvement?

**Comment by Alisamix** [comment]
Only machines with the M1 chip.

**Comment by andportnoy** [comment]
@Alisamix ![](https://machinelearning.apple.com/_next/static/images/mac-pro-tensorflow-graph-3db5429cad8a80bc337d5c9a8c4a07db.png)

**Comment by bryanlimy** [comment]
I just tested it out on my MacBook Pro with the Radeon Pro 560X dGPU, and it does train on the dGPU. My computer complete crashed when I try to train a transformer tho. https://twitter.com/bryanlimy/status/1329170392653713415?s=21

**Comment by jtkiley** [comment]
@andportnoy

> Will MacBook Pros with AMD GPUs see a performance improvement?

The [blog post](https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html) says this (and uses a Mac Pro as an Intel example):

>In the graphs below, you can see how Mac-optimized TensorFlow 2.4 can deliver huge performance increases on both M1- and Intel-powered Macs with popular models.

Looks like good news for all of us who have been waiting for this!

**Comment by anna-tikhonova** [comment]
> I just tested it out on my MacBook Pro with the Radeon Pro 560X dGPU, and it does train on the dGPU (a simple CNN on CIFAR10). My MacBook complete crashed when I try to train a transformer tho 😅
> https://twitter.com/bryanlimy/status/1329170392653713415?s=21

@bryanlimy Is it possible for you to share your transformer model with us, so we can investigate the crash you are seeing? Thank you!

**Comment by bryanlimy** [comment]
@anna-tikhonova https://github.com/bryanlimy/tf2-transformer-chatbot

I added 
```
from tensorflow.python.compiler.mlcompute import mlcompute
mlcompute.set_mlc_device(device_name='gpu')
```
to the top of `main.py`. Then run the training with the command 'python main.py --batch_size 64 --epochs 10 --max_samples 50000'.

**Comment by anna-tikhonova** [comment]
This fork is suitable for both Intel-based Macs and Macs with the M1 chip, running macOS 11.0+. This includes machines with AMD GPUs.

**Comment by andportnoy** [comment]
@anna-tikhonova Got it, that's exciting news! Thank you, closing issue.
