### ISSUE TITLE
getting this error when using transfer learning. 

### ISSUE THREAD

**Issue by vivek-ram** [apple/tensorflow_macos#219]
<img width="1680" alt="Screenshot 2021-03-29 at 12 11 00 am" src="https://user-images.githubusercontent.com/56974835/113187206-7dc47c80-9250-11eb-9a72-4794481f6de2.png">

**Comment by calvalugo** [comment]
The training models exceed the memory capacity of your Mac, you'll need to manage the complexity to prevent this from happening.

**Comment by vivek-ram** [comment]
thanks I solved it.
