### ISSUE TITLE
M1 Importing Tensorflow from venv Kills Kernel

### ISSUE THREAD

**Issue by dgupgu** [apple/tensorflow_macos#223]
I download TensorFlow within the virtual environment :
1. % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
2. . "/Users/darrengu/tensorflow_macos_venv/bin/activate"

I then open a Jupyter Notebook that has a cell with the import statement "import tensorflow as tf"
3. pip install jupyterlab
4. python -m notebook

When I run the cell that imports tensorflow, my Kernel dies. Any fixes for this?

**Comment by missperovaz** [comment]
1. make sure your terminal is not being opened using Rosetta
2. to install packages for your environment use:
pip install --upgrade -t "${VIRTUAL_ENV}/lib/python3.8/site-packages/" PACKAGE_NAME

**Comment by dgupgu** [comment]
Thanks! Making sure to run terminal without Rosetta (using ARM, and not x86, architecture) worked for me
