### ISSUE TITLE
ML Compute: Cannot Set Device

### ISSUE THREAD

**Issue by DLWCMD** [apple/tensorflow_macos#256]
By following the guidance from https://github.com/apple/tensorflow_macos, I was able to create a Conda environment for the ML_Compute version of TensorFlow.

I then ran a test script (see attached) to test GPU performance, but regardless of settings (either 'gpu' or 'any'), the code is run on my CPU. Note in the script i disable eager execution, as instructed. 

The image below summarizes my operating environment.

Thanks for your help.

[MLC_Test_1.py.zip](https://github.com/apple/tensorflow_macos/files/6447661/MLC_Test_1.py.zip)

<img width="291" alt="Screen Shot 2021-05-09 at 9 52 11 AM" src="https://user-images.githubusercontent.com/48808570/117574695-4dbc9480-b0ac-11eb-8829-0e52eacede95.png">

**Comment by ManuelSchneid3r** [comment]
#235 please close this one
