### ISSUE TITLE
Error while running keras.sequential

### ISSUE THREAD

**Issue by Anusha1408** [apple/tensorflow_macos#267]
~/miniforge3/envs/apple_tensorflow/lib/python3.8/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

~/miniforge3/envs/apple_tensorflow/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in __array__(self)
    850 
    851   def __array__(self):
--> 852     raise NotImplementedError(
    853         "Cannot convert a symbolic Tensor ({}) to a numpy array."
    854         " This error may indicate that you're trying to pass a Tensor to"

NotImplementedError: Cannot convert a symbolic Tensor (random_rotation_1/rotation_matrix/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Can anyone help in solving this?

**Comment by devnev39** [comment]
Try installing numpy 1.19.5 instead of 1.20.0.

**Comment by Anusha1408** [comment]
solved thanks
worked for me too
