### ISSUE TITLE
incompatible cpu-subtype error

### ISSUE THREAD

**Issue by lutchu** [apple/tensorflow_macos#34]
I ran the installer script and activated the virtualenv as mentioned at the end of the installation.

At the python interpreter I get the following error. Is there some other package to install to get this working on an M1 Mac?

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: incompatible cpu-subtype: 0x00000000 in /Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
	/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: incompatible cpu-subtype: 0x00000000 in /Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: incompatible cpu-subtype: 0x00000000 in /Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
	/Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: incompatible cpu-subtype: 0x00000000 in /Users/macuser/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by lutchu** [comment]
I finally managed to get this working on an M1 Mac under a conda managed env. In case anyone else hits this - try the conda installation path that's been mentioned in older posts.

**Comment by deadpoolchick2008** [comment]
😎✌️

**Comment by deadpoolchick2008** [comment]
events {}

http {
	
	server {
    	listen 443 ssl http2;
    	server_name 165.22.19.194; # замените на собственный домен или IP адрес
    	ssl on;
		ssl_certificate /etc/nginx/ssl/domain.crt;
		ssl_certificate_key /etc/nginx/ssl/domain.key;
		root /home/TestNginx;
		server_tokens off;
		
    	location /
		{
			sendfile on;
			default_type audio/mpeg;
			root /media;
		}
	}
}

**Comment by anna-tikhonova** [comment]
Thank you for reporting this issue. I'm glad you got it resolved!

**Comment by hoytak** [comment]
To clarify what is happening here for others encountering this issue. 

There are two cpu subtypes for binary files on the M1, arm64 and arm64e. Trying to mix the two results in the error you see. For this pre-release version, we're focusing support on the arm64 version of python in the Xcode Command Line Tools, and the included wheel does not include an arm64e slice.  To make sure you have the correct version of python run `file $(which python)` and it should display an arm64 slice, not an arm64e slice.  

If you encounter this problem, install the Python version from [Xcode Command Line Tools](https://developer.apple.com/download/more/?=command%20line%20tools), then pass the path to that version into the install script using `--python=/Library/Developer/CommandLineTools/usr/bin/python3`.

**Comment by ssingh496** [comment]
@hoytak  I have the new Mac1 - Darwin MacBook-Air.broadband 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64

I am trying to install the TF using below command but facing the same problem of this thread. 
- /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
=================
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/sandeepsingh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

=========
When I am trying to check the python it says -
(tensorflow_macos_venv) sandeepsingh@MacBook-Air ~ % file $(which python)
/Users/sandeepsingh/tensorflow_macos_venv/bin/python: Mach-O 64-bit executable x86_64

Any suggestions ?
