### ISSUE TITLE
message : rebuild TensorFlow with the appropriate compiler flags

### ISSUE THREAD

**Issue by fassifihri** [apple/tensorflow_macos#57]
after installing, to test i launch python and the commands
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
i have the message
I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Thank you for the guidance!

**Comment by fassifihri** [comment]
solved

**Comment by WasifRaza123** [comment]
facing same problem
How have you solved?

**Comment by MareSeestern** [comment]
> 
> 
> solved

how?

**Comment by fassifihri** [comment]
The problem occurred for me because I have tested with a code copies and pasted from Google chrome to terminal. but when I typed the code the problem disappear.

**Comment by JapinderSandhu** [comment]
> The problem occurred for me because I have tested with a code copies and pasted from Google chrome to terminal. but when I typed the code the problem disappear.

This did not work for me I am still getting the same errors 

Enviornment:
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  Memory:	16 GB


Python 3.8.5
tensorflow             2.4.1

**Comment by jmilotaylor** [comment]
same issue here

Model Name: MacBook Pro
Model Identifier: MacBookPro
Processor Name: Intel Core i5
Processor Speed: 2GHz
Memory: 16 GB

Python 3.8.6
tensorflow 2.4.1

**Comment by lukaixuan** [comment]
same issue here , how do you solved?

**Comment by kevinyaoxm** [comment]
trying building your tensorflow from source with "--config=mkl -c opt --copt=-march=native" options
ref: https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html

**Comment by kishoreKunisetty** [comment]
I am also facing the same issue 
can anyone who resolved this issue can provide me with a detailed solution

**Comment by shrutz510** [comment]
Still facing the same issue
