### ISSUE TITLE
RuntimeError: MLCompute device must be set before initialization

### ISSUE THREAD

**Issue by cmacphillamy** [apple/tensorflow_macos#58]
Hello,

This may not be a bug but I can't seem to find a way to resolve this.

1. I install Tensorflow as described in the Readme.

2. Using PyCharm I run:
``` 
import tensorflow as tf
import tensorflow_addons
import tensorboard


#%%

hello = tf.constant("Hello World")
print(hello)

#%%

#Import mlcompute module to use the optional set_mlc_device API for device selection with ML Compute.
from tensorflow.python.compiler.mlcompute import mlcompute
mlcompute.set_mlc_device(device_name= 'gpu')
```

It's at the last line where I get the following error:

`RuntimeError: MLCompute device must be set before initialization`

Does anyone have any suggestions on how to fix this?

Thank you in advance.

**Comment by dmmajithia** [comment]
The error means that you need to set the MLCompute device (gpu or cpu) before initializing any tensors.
So just move the last 2 lines above the "hello" assignment/initialization and it should work.

**Comment by cmacphillamy** [comment]
> The error means that you need to set the MLCompute device (gpu or cpu) before initializing any tensors.
> So just move the last 2 lines above the "hello" assignment/initialization and it should work.

I'm such a noob! Thank you so much! :D

**Comment by ElaheHkh** [comment]
I also have this problem but this solution didn't work for me😭😭😭😭

**Comment by Anusha1408** [comment]
not working for me also , can anyone help?
