### ISSUE TITLE
M1 install tensorflow2.4.0 have some problems

### ISSUE THREAD

**Issue by liyinglw** [apple/tensorflow_macos#59]
When after installing tensorflow2.4.0, I can run successfully in the terminal, but I import tensorflow in pycharm, it has some problems. Otherwise, I input pip install pandas in the terminal, it shows some errors. Could you please help me solve these questions? Thank you very much!

**Comment by hoytak** [comment]
Hello @liyinglw, 

Please try the latest version and see if you still have issues.

**Comment by hoytak** [comment]
Hey @liyinglw -- did the latest installer fix your problems?  If not, please reopen the issue and let me know.
