### ISSUE TITLE
ERROR: numpy-1.18.5-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by kukupigs** [apple/tensorflow_macos#61]
ERROR: numpy-1.18.5-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

**Comment by seongilp** [comment]
#46

**Comment by hoytak** [comment]
Hello.  I believe this should be fixed in the latest installer.  Please let me know if you still have issues.  Thank you!
