### ISSUE TITLE
No GPU found when execute "tf.config.list_physical_devices('GPU')"

### ISSUE THREAD

**Issue by duwangthefirst** [apple/tensorflow_macos#70]
when I execute:
```
import tensorflow as tf

tf.config.list_physical_devices('GPU')
```
the result is:
```
[]
```
So I'm wondering what the project's highlights are, Since GPU-related feature is not available.

**Comment by duwangthefirst** [comment]
Or is Apple's ML framework powerful enough to take fully advantage of all local computing capability (including both CPU and GPU) ?

**Comment by anna-tikhonova** [comment]
If you run your code as-is or set the device type to 'any', ML Compute queries the available devices on your system and selects the best device(s) for training your network. If you turn on logging (see README), you can see which device(s) ML Compute is using.

**Comment by watjurk** [comment]
It seems that this issue should be marked as closed @duwangthefirst  @anna-tikhonova.

Thanks!
