### ISSUE TITLE
Will an AMD eGPU connected to an Intel MacBook Pro 16 be used by tensorflow?

### ISSUE THREAD

**Issue by djr1028** [apple/tensorflow_macos#78]
Does this version of tensorflow support eGPUs?

**Comment by anna-tikhonova** [comment]
Yes, we accelerate TensorFlow with ML Compute and ML Compute will use your eGPU.

**Comment by djr1028** [comment]
Thanks. For a MacBook Pro 16, which contains its own dedicated AMD GPU in addition to integrated GPU, would tensorflow/ML Compute consider that a multi-gpu configuration and try to use both dedicated and eGPUs, or just the eGPU? If the first, then could there be a way to force it to use just the eGPU?

**Comment by djr1028** [comment]
> Yes, we accelerate TensorFlow with ML Compute and ML Compute will use your eGPU.

Thanks. For a MacBook Pro 16, which contains its own dedicated AMD GPU in addition to integrated GPU, would tensorflow/ML Compute consider that a multi-gpu configuration and try to use both dedicated and eGPUs, or just the eGPU? If the first, then could there be a way to force it to use just the eGPU?

**Comment by anna-tikhonova** [comment]
In this situation, ML Compute will select the eGPU. This is not a multi-GPU scenario, because transferring data between the discrete GPU and the eGPU can be expensive.

**Comment by djr1028** [comment]
Thank you. That's the desired behavior.

**Comment by djr1028** [comment]
Thank you. That's the desired behavior.
