### ISSUE TITLE
import tensorflow --> Illegal instruction: 4

### ISSUE THREAD

**Issue by gmarceca** [apple/tensorflow_macos#81]
Hello,
I've recently got a Macbook pro v11 and I cannot import tensorflow after following these steps:

1. Get the TF for M1 tarball from [here](https://github.com/apple/tensorflow_macos/releases/tag/v0.1alpha1).
2. Install TF for M1 like this: /bin/bash tensorflow_macos/install_venv.sh -p --python=/Library/Developer/CommandLineTools/usr/bin/python3
...
TensorFlow and TensorFlow Addons with ML Compute for macOS 11.0 successfully installed.
3. activate environment: . ~/tensorflow_macos/bin/activate
4. python -c "import tensorflow"

Illegal instruction: 4

Did you have this issue?
Thanks very much!

**Comment by HanxiSun** [comment]
I got 
`zsh:` illegal hardware instruction  python`
Not sure if it is the same issue though

**Comment by gmarceca** [comment]
Hello HanxiSun,
Thanks very much for your reply, unfortunately "open using Rosetta" is already switched off in my terminal. So I might have another issue...

**Comment by gmarceca** [comment]
> Similar here. I got
> `zsh: illegal hardware instruction python`
> when I try import tensorflow
> 
> UPDATE: My bad, I installed TF with Rosetta terminal. After switching off "open using Rosetta" in my terminal "Get Info", I followed the instruction to install TF again and it worked!

HanxiSun

**Comment by gmarceca** [comment]
> > Similar here. I got
> > `zsh: illegal hardware instruction python`
> > when I try import tensorflow
> > UPDATE: My bad, I installed TF with Rosetta terminal. After switching off "open using Rosetta" in my terminal "Get Info", I followed the instruction to install TF again and it worked!
> 
> HanxiSun

Thanks very much for your reply, unfortunately "open using Rosetta" is already switched off in my terminal, so I might have another issue...

**Comment by gmarceca** [comment]
> Similar here. I got
> `zsh: illegal hardware instruction python`
> when I try import tensorflow
> 
> UPDATE: My bad, I installed TF with Rosetta terminal. After switching off "open using Rosetta" in my terminal "Get Info", I followed the instruction to install TF again and it worked!

Thanks very much for your reply, unfortunately "open using Rosetta" is already switched off in my terminal, so I might have another issue...

**Comment by gmarceca** [comment]
Hello,
I solved the issue but I don't know the reason, and it's a bit strange... here are the steps I did:
1. I enabled the option "Open using Rosetta" from "terminal --> Get Info"
2. Closed and open the terminal
3. Installed tensorflow_macos by running: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
4. python -c "import tensorflow" now produced the error pointed here https://github.com/apple/tensorflow_macos/issues/83#issue-771526404
5. Then I disabled "Open using Rosetta", close and open the terminal again. Curiously, the error in https://github.com/apple/tensorflow_macos/issues/83#issue-771526404 persisted...
6. Finally I downloaded and installed tensorflow_macos but using python 3.8 from the CommandLineTools, following the 
4 steps I mentioned in my first post above. Magic...

**Comment by gmarceca** [comment]
> Hello,
> I solved the issue but I don't know the reason, and it's a bit strange... here are the steps I did:
> 
>     1. I enabled the option "Open using Rosetta" from "terminal --> Get Info"
> 
>     2. Closed and open the terminal
> 
>     3. Installed tensorflow_macos by running: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
> 
>     4. python -c "import tensorflow" now produced the error pointed here [#83 (comment)](https://github.com/apple/tensorflow_macos/issues/83#issue-771526404)
> 
>     5. Then I disabled "Open using Rosetta", close and open the terminal again. Curiously, the error in [#83 (comment)](https://github.com/apple/tensorflow_macos/issues/83#issue-771526404) persisted...
> 
>     6. Finally I downloaded and installed tensorflow_macos but using python 3.8 from the CommandLineTools, following the
>        4 steps I mentioned in my first post above. Magic...

**Comment by vnesh-san** [comment]
> Hello,
> I solved the issue but I don't know the reason, and it's a bit strange... here are the steps I did:
> 
> 1. I enabled the option "Open using Rosetta" from "terminal --> Get Info"
> 2. Closed and open the terminal
> 3. Installed tensorflow_macos by running: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
> 4. python -c "import tensorflow" now produced the error pointed here [#83 (comment)](https://github.com/apple/tensorflow_macos/issues/83#issue-771526404)
> 5. Then I disabled "Open using Rosetta", close and open the terminal again. Curiously, the error in [#83 (comment)](https://github.com/apple/tensorflow_macos/issues/83#issue-771526404) persisted...
> 6. Finally I downloaded and installed tensorflow_macos but using python 3.8 from the CommandLineTools, following the
>    4 steps I mentioned in my first post above. Magic...

Yeah! I disabled Rosetta and then only followed the exact procedure. It still through me an error. One thing I forgot to do was use the --python flag to point to arm64 python3.8 from Xcode Developer Tools. Once I did that, I was able to install it successfully!!

**Comment by theomeb** [comment]
Seems to be quite related to this issue https://github.com/apple/tensorflow_macos/issues/65.

You can check whether you are running your terminal in arm64 or x86_64 with `uname -m` or within a python shell:
```
import platform
print(platform.uname())
```

**Comment by Aatiya25** [comment]
Can anyone explain step 6: Finally I downloaded and installed tensorflow_macos but using python 3.8 from the CommandLineTools, following the
4 steps I mentioned in my first post above. Magic...

How to use commandlinetool and then again install TensorFlow using python3.8. I am stuck at this point and nothing is working out

**Comment by gmarceca** [comment]
You can specify the python from CommandLineTools via the --python flag as follows:
/bin/bash tensorflow_macos/install_venv.sh -p --python=/Library/Developer/CommandLineTools/usr/bin/python3
Hope it works for you.

**Comment by Aatiya25** [comment]
That worked for me! thanks a mil @gmarceca . Did anyone try Pytorch on the same environment? I know most of the packages are not compatible but I want to use both TensorFlow and Pytorch at the same time for a priority project at work and I am just using M1. If anyone has any suggestions please reply ASAP.

**Comment by xiaoming124** [comment]
> You can specify the python from CommandLineTools via the --python flag as follows:
> /bin/bash tensorflow_macos/install_venv.sh -p --python=/Library/Developer/CommandLineTools/usr/bin/python3
> Hope it works for you.

Thanks for your comment, That worked for me!!!!!

**Comment by jlnerd** [comment]
I ran into this issue as well when trying to use tensorflow from an anaconda installed version of python (`/opt/anaconda3/bin/python`). 

Once I executed from the `/Library/Developer/CommandLineTools/usr/bin/python3` version of python, things worked.

So, make sure you are executing the python version installed from [Xcode Command Line Tools.](https://developer.apple.com/download/more/?=command%20line%20tools)
