### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by federicolucca** [apple/tensorflow_macos#98]
Good morning

There are some updates? On my M1 mac doesn't work
Thanks

**Comment by anna-tikhonova** [comment]
Thank you very much for reaching out. Could you please provide a reproducible test case, so we can see what you are trying to do and investigate locally?

**Comment by federicolucca** [comment]
I found the solution. I must use the official python version from Apple, 3.8.2 . 
The trouble now is about each dependencies , i must wait for the updates from all the developers like OpenCV
Thanks

**Comment by BenjaminChoou** [comment]
> I found the solution. I must use the official python version from Apple, 3.8.2 .
> The trouble now is about each dependencies , i must wait for the updates from all the developers like OpenCV
> Thanks

You should either compile OpenCV from source or use [conda-forge](https://anaconda.org/conda-forge/opencv). Try it.

**Comment by watjurk** [comment]
It seems that this issue should be marked as closed @federicolucca @anna-tikhonova.

Thanks!

**Comment by federicolucca** [comment]
Yes, i switched to conda and it's working. Only on CPU but it works
